/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: invitation.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as invitation_pb from './invitation_pb'; // proto import: "invitation.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class InvitationClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateInvitation = new grpcWeb.MethodDescriptor(
    '/Invitation/CreateInvitation',
    grpcWeb.MethodType.UNARY,
    invitation_pb.CreateInvitationRequest,
    invitation_pb.CreateInvitationResponse,
    (request: invitation_pb.CreateInvitationRequest) => {
      return request.serializeBinary();
    },
    invitation_pb.CreateInvitationResponse.deserializeBinary
  );

  createInvitation(
    request: invitation_pb.CreateInvitationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<invitation_pb.CreateInvitationResponse>;

  createInvitation(
    request: invitation_pb.CreateInvitationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: invitation_pb.CreateInvitationResponse) => void): grpcWeb.ClientReadableStream<invitation_pb.CreateInvitationResponse>;

  createInvitation(
    request: invitation_pb.CreateInvitationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: invitation_pb.CreateInvitationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Invitation/CreateInvitation',
        request,
        metadata || {},
        this.methodDescriptorCreateInvitation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Invitation/CreateInvitation',
    request,
    metadata || {},
    this.methodDescriptorCreateInvitation);
  }

  methodDescriptorUpdateInvitation = new grpcWeb.MethodDescriptor(
    '/Invitation/UpdateInvitation',
    grpcWeb.MethodType.UNARY,
    invitation_pb.UpdateInvitationRequest,
    google_protobuf_empty_pb.Empty,
    (request: invitation_pb.UpdateInvitationRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  updateInvitation(
    request: invitation_pb.UpdateInvitationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  updateInvitation(
    request: invitation_pb.UpdateInvitationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  updateInvitation(
    request: invitation_pb.UpdateInvitationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Invitation/UpdateInvitation',
        request,
        metadata || {},
        this.methodDescriptorUpdateInvitation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Invitation/UpdateInvitation',
    request,
    metadata || {},
    this.methodDescriptorUpdateInvitation);
  }

  methodDescriptorAcceptInvitation = new grpcWeb.MethodDescriptor(
    '/Invitation/AcceptInvitation',
    grpcWeb.MethodType.UNARY,
    invitation_pb.AcceptInvitationRequest,
    google_protobuf_empty_pb.Empty,
    (request: invitation_pb.AcceptInvitationRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  acceptInvitation(
    request: invitation_pb.AcceptInvitationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  acceptInvitation(
    request: invitation_pb.AcceptInvitationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  acceptInvitation(
    request: invitation_pb.AcceptInvitationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Invitation/AcceptInvitation',
        request,
        metadata || {},
        this.methodDescriptorAcceptInvitation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Invitation/AcceptInvitation',
    request,
    metadata || {},
    this.methodDescriptorAcceptInvitation);
  }

  methodDescriptorDeclineInvitation = new grpcWeb.MethodDescriptor(
    '/Invitation/DeclineInvitation',
    grpcWeb.MethodType.UNARY,
    invitation_pb.DeclineInvitationRequest,
    google_protobuf_empty_pb.Empty,
    (request: invitation_pb.DeclineInvitationRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  declineInvitation(
    request: invitation_pb.DeclineInvitationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  declineInvitation(
    request: invitation_pb.DeclineInvitationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  declineInvitation(
    request: invitation_pb.DeclineInvitationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Invitation/DeclineInvitation',
        request,
        metadata || {},
        this.methodDescriptorDeclineInvitation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Invitation/DeclineInvitation',
    request,
    metadata || {},
    this.methodDescriptorDeclineInvitation);
  }

  methodDescriptorDeleteInvitation = new grpcWeb.MethodDescriptor(
    '/Invitation/DeleteInvitation',
    grpcWeb.MethodType.UNARY,
    invitation_pb.DeleteInvitationRequest,
    google_protobuf_empty_pb.Empty,
    (request: invitation_pb.DeleteInvitationRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteInvitation(
    request: invitation_pb.DeleteInvitationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteInvitation(
    request: invitation_pb.DeleteInvitationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteInvitation(
    request: invitation_pb.DeleteInvitationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Invitation/DeleteInvitation',
        request,
        metadata || {},
        this.methodDescriptorDeleteInvitation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Invitation/DeleteInvitation',
    request,
    metadata || {},
    this.methodDescriptorDeleteInvitation);
  }

}

