/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: message.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as message_pb from './message_pb'; // proto import: "message.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class MessageClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateMessage = new grpcWeb.MethodDescriptor(
    '/Message/CreateMessage',
    grpcWeb.MethodType.UNARY,
    message_pb.CreateMessageRequest,
    message_pb.CreateMessageResponse,
    (request: message_pb.CreateMessageRequest) => {
      return request.serializeBinary();
    },
    message_pb.CreateMessageResponse.deserializeBinary
  );

  createMessage(
    request: message_pb.CreateMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<message_pb.CreateMessageResponse>;

  createMessage(
    request: message_pb.CreateMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: message_pb.CreateMessageResponse) => void): grpcWeb.ClientReadableStream<message_pb.CreateMessageResponse>;

  createMessage(
    request: message_pb.CreateMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: message_pb.CreateMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Message/CreateMessage',
        request,
        metadata || {},
        this.methodDescriptorCreateMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Message/CreateMessage',
    request,
    metadata || {},
    this.methodDescriptorCreateMessage);
  }

  methodDescriptorUpdateMessage = new grpcWeb.MethodDescriptor(
    '/Message/UpdateMessage',
    grpcWeb.MethodType.UNARY,
    message_pb.UpdateMessageRequest,
    google_protobuf_empty_pb.Empty,
    (request: message_pb.UpdateMessageRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  updateMessage(
    request: message_pb.UpdateMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  updateMessage(
    request: message_pb.UpdateMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  updateMessage(
    request: message_pb.UpdateMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Message/UpdateMessage',
        request,
        metadata || {},
        this.methodDescriptorUpdateMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Message/UpdateMessage',
    request,
    metadata || {},
    this.methodDescriptorUpdateMessage);
  }

  methodDescriptorDeleteMessage = new grpcWeb.MethodDescriptor(
    '/Message/DeleteMessage',
    grpcWeb.MethodType.UNARY,
    message_pb.DeleteMessageRequest,
    google_protobuf_empty_pb.Empty,
    (request: message_pb.DeleteMessageRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteMessage(
    request: message_pb.DeleteMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteMessage(
    request: message_pb.DeleteMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteMessage(
    request: message_pb.DeleteMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Message/DeleteMessage',
        request,
        metadata || {},
        this.methodDescriptorDeleteMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Message/DeleteMessage',
    request,
    metadata || {},
    this.methodDescriptorDeleteMessage);
  }

}

