// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.27.1
// source: teamy/message/priority.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_PRIORITY_URGENT Priority = 0
	Priority_PRIORITY_HIGH   Priority = 1
	Priority_PRIORITY_MEDIUM Priority = 2
	Priority_PRIORITY_LOW    Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_URGENT",
		1: "PRIORITY_HIGH",
		2: "PRIORITY_MEDIUM",
		3: "PRIORITY_LOW",
	}
	Priority_value = map[string]int32{
		"PRIORITY_URGENT": 0,
		"PRIORITY_HIGH":   1,
		"PRIORITY_MEDIUM": 2,
		"PRIORITY_LOW":    3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_teamy_message_priority_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_teamy_message_priority_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_teamy_message_priority_proto_rawDescGZIP(), []int{0}
}

var File_teamy_message_priority_proto protoreflect.FileDescriptor

var file_teamy_message_priority_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x65, 0x61, 0x6d, 0x79, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x59,
	0x0a, 0x08, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52,
	0x49, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x52, 0x47, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x50, 0x52, 0x49, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x48, 0x49, 0x47, 0x48,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x50, 0x52, 0x49, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x4d,
	0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x52, 0x49, 0x4f, 0x52,
	0x49, 0x54, 0x59, 0x5f, 0x4c, 0x4f, 0x57, 0x10, 0x03, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x79, 0x61, 0x70, 0x70,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x67,
	0x6f, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x79, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teamy_message_priority_proto_rawDescOnce sync.Once
	file_teamy_message_priority_proto_rawDescData = file_teamy_message_priority_proto_rawDesc
)

func file_teamy_message_priority_proto_rawDescGZIP() []byte {
	file_teamy_message_priority_proto_rawDescOnce.Do(func() {
		file_teamy_message_priority_proto_rawDescData = protoimpl.X.CompressGZIP(file_teamy_message_priority_proto_rawDescData)
	})
	return file_teamy_message_priority_proto_rawDescData
}

var file_teamy_message_priority_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_teamy_message_priority_proto_goTypes = []interface{}{
	(Priority)(0), // 0: Priority
}
var file_teamy_message_priority_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teamy_message_priority_proto_init() }
func file_teamy_message_priority_proto_init() {
	if File_teamy_message_priority_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teamy_message_priority_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teamy_message_priority_proto_goTypes,
		DependencyIndexes: file_teamy_message_priority_proto_depIdxs,
		EnumInfos:         file_teamy_message_priority_proto_enumTypes,
	}.Build()
	File_teamy_message_priority_proto = out.File
	file_teamy_message_priority_proto_rawDesc = nil
	file_teamy_message_priority_proto_goTypes = nil
	file_teamy_message_priority_proto_depIdxs = nil
}
